function [nRows, nCols] = getSubplotLayout(nCh)
% designs "optimal" layout for subplots (covers whole figure)
% up to 300 subplots (more makes no sense anyways)

% (c) Jiri, Mar16

if nCh == 1
    nRows = 1;
    nCols = 1;
elseif nCh == 2
    nRows = 1;
    nCols = 2;
elseif nCh == 3
    nRows = 1;
    nCols = 3;
elseif nCh <= 6
    nRows = 2;
    nCols = 3; 
elseif nCh <= 8
    nRows = 2;
    nCols = 4;     
elseif nCh <= 12
    nRows = 3;
    nCols = 4;
elseif nCh <= 15
    nRows = 3;
    nCols = 5;
elseif nCh <= 20
    nRows = 4;
    nCols = 5;    
elseif nCh <= 24
    nRows = 4;
    nCols = 6;
elseif nCh <= 28
    nRows = 4;
    nCols = 7;
elseif nCh <= 30
    nRows = 5;
    nCols = 6;    
elseif nCh <= 35
    nRows = 5;
    nCols = 7;
elseif nCh <= 40
    nRows = 5;
    nCols = 8;  
elseif nCh <= 42
    nRows = 6;
    nCols = 7;      
elseif nCh <= 48
    nRows = 6;
    nCols = 8;
elseif nCh <= 56
    nRows = 7;
    nCols = 8;    
elseif nCh <= 63
    nRows = 7;
    nCols = 9;
elseif nCh <= 64
    nRows = 8;
    nCols = 8;    
elseif nCh <= 72
    nRows = 8;
    nCols = 9;    
elseif nCh <= 80
    nRows = 8;
    nCols = 10;
elseif nCh <= 88
    nRows = 8;
    nCols = 11;   
elseif nCh <= 90
    nRows = 9;
    nCols = 10;       
elseif nCh <= 99
    nRows = 9;
    nCols = 11;
elseif nCh <= 100
    nRows = 10;
    nCols = 10;
elseif nCh <= 112
    nRows = 8;
    nCols = 14;    
elseif nCh <= 126
    nRows = 9;
    nCols = 14;        
elseif nCh <= 128
    nRows = 8;
    nCols = 16;
elseif nCh <= 140
    nRows = 10;
    nCols = 14;
elseif nCh <= 154
    nRows = 11;
    nCols = 14;
elseif nCh <= 165
    nRows = 11;
    nCols = 15;    
elseif nCh <= 168
    nRows = 12;
    nCols = 14;        
elseif nCh <= 180
    nRows = 12;
    nCols = 15;
elseif nCh <= 195
    nRows = 13;
    nCols = 15;    
elseif nCh <= 208
    nRows = 13;
    nCols = 16;    
elseif nCh <= 221
    nRows = 13;
    nCols = 17;
else
    nRows = 15;
    nCols = 20;    
end
