function str_title = plotFC_getTitle(chGroups, src, trg, clzLabel, fcName)
% return title for FC plots

% (c) Jiri, Oct23

if nargin < 5
    str_title = '';
else
    str_title = [fcName ': '];  % connectivity name
end

if nargin == 3 || isempty(clzLabel)
    str_title = [ str_title ...
        getAbbreviation(chGroups.nn_name{src}) '(' num2str(size(chGroups.ch_names{src},2)) ')' ...
        ' -> ' ...
        getAbbreviation(chGroups.nn_name{trg}) '(' num2str(size(chGroups.ch_names{trg},2)) ')' ...
%         ' : ' clzLabel ...
        ];
else
    str_title = [ str_title ...
        getAbbreviation(chGroups.nn_name{src}) '(' num2str(size(chGroups.ch_names{src},2)) ')' ...
        ' -> ' ...
        getAbbreviation(chGroups.nn_name{trg}) '(' num2str(size(chGroups.ch_names{trg},2)) ')' ...
        ' : ' clzLabel ...
        ];
end