%% triggering on phase locked maxima
timeStep = 0.02;  % in [s]
paramsEcog;
% params.trigResp = struct(...
%     'signalType', 'EcogGrid', ...
%     'selectedChnls', {{'all'}}, ... % 'all','prefrontal','broca','premotor','primsensory','ipcPF','ipcPFm'
%     'excludedChnls', [], ...
%     'dataProcessing', {{'car','bp_hiPass', 'norm2std'}}, ...  % preprocessing of predictor signal
%     'saveProcessing', true ...
%     );
params.bp_loPass = struct(...
    'filterType', 'low', ...
    'butterOrder', 4, ...               % butterworth filter order
    'freqBand', [0 1.5] ...             % low pass: [loF, hiF] in Hz 
    );
params.downsample = struct(...
    'dsRate', ceil(timeStep*params.amp.srate) ...
    );
params.trigResp = struct(...
    'signalType', 'Traj', ...
    'selectedChnls', {{'all'}}, ... % 'all','prefrontal','broca','premotor','primsensory','ipcPF','ipcPFm'
    'excludedChnls', [], ...
    'dataProcessing', {{'norm2std', 'bp_loPass', 'downsample'}}, ...  % preprocessing of predictor signal
    'saveProcessing', true ...
    );
% params.trigResp = struct(...
%     'signalType', 'EcogGrid', ...
%     'selectedChnls', {{'all'}}, ... % 'all','prefrontal','broca','premotor','primsensory','ipcPF','ipcPFm'
%     'excludedChnls', [], ...
%     'dataProcessing', {{'car', 'bp_hiPass', 'bp_loPass', 'downsample'}}, ...  % preprocessing of predictor signal
%     'saveProcessing', true ...
%     );

params.triggering = struct(...
    'doTriggering', true, ...
    'time2cut', [-5, 5], ...
    'response', params.trigResp, ...
    'trigMethod', 'phaseLockedMax', ...             % name MUST match a params field! options: locExtrema, fromParadigm
    'threshold', 1:0.2:3.0, ...
    'plotDetection', true ...
    );
params.phaseLockedMax = struct(...
    'nSurrogates', 200, ...
    'pSignif', 0.01 ...
    );
params.regressMethod.doLinRegression = false;

outName = 'trigTrajPhaseLock';

wnExp_WN1_ecog;
%wnExp_WN2_ecog2;
%wnExp_WN3_ecog3_train;